global:
  team: "platform"
  defaultImageName: "pay-log-aggregator"
  defaultTag: "latest"
  
  image:
    registry: ""
    repository: "pay-log-aggregator"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  
  environment:
    ELASTICSEARCH_HOST: "elasticsearch"
    ELASTICSEARCH_PORT: "9200"
    ELASTICSEARCH_INDEX_PREFIX: "pay-logs"
    BATCH_SIZE: "100"
    SEARCH_TIMEOUT: "30s"
    MAX_SEARCH_RESULTS: "1000"
    RETENTION_DAYS: "90"
    COMPRESSION_ENABLED: "true"
  
  configurations:
    enabled: false
    values: {}

deployment:
  enabled: true
  
  image:
    name: "pay-log-aggregator"
    tag: ""  
    
  containerPort: 8000
  
  extraContainerPorts:
    - name: metrics
      port: 9090
      protocol: TCP
  
  createServiceAccount: true
  serviceAccountAnnotations: {}

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"

  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "200m"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
          - type: Percent
            value: 100
            periodSeconds: 15
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
  
  deploymentStrategy:
    type: "RollingUpdate"
    maxSurge: 50%
    maxUnavailable: 25%
  
  livenessProbe:
    enabled: true
    timeoutSeconds: 5
    periodSeconds: 10
    httpGet:
      path: "/health"
      
  readinessProbe:
    enabled: true
    timeoutSeconds: 5
    periodSeconds: 10
    httpGet:
      path: "/health"
      
  startupProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 10
    httpGet:
      path: "/health"
      
  preStopHook:
    enabled: true
    preStopSeconds: 10

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
  annotations: {}
  
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: pay-log-aggregator.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

configMap:
  enabled: true
  data:
    elasticsearch.yaml: |
      host: elasticsearch
      port: 9200
      index_prefix: pay-logs

podDisruptionBudget:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: false
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: pay-log-aggregator
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 9200 
        - protocol: UDP
          port: 53    

rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["configmaps", "secrets"]
      verbs: ["get", "list"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]

security:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

podSecurityContext:
  fsGroup: 1000

elasticsearch:
  enabled: true
  host: "elasticsearch"
  port: 9200
  credentials:
    username: ""
    password: ""
    existingSecret: ""

prometheus:
  enabled: true
  port: 9090
  path: "/metrics"
  interval: "30s"

monitoring:
  serviceMonitor:
    enabled: true
    namespace: ""
    interval: "30s"
    scrapeTimeout: "10s"
    path: "/metrics"
    labels: {}
    annotations: {}
    metricRelabelings: []
    relabelings: []