{{- if .Values.deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pay-log-aggregator.fullname" . }}
  labels:
    {{- include "pay-log-aggregator.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pay-log-aggregator.fullname" . }}
  minReplicas: {{ required "value 'deployment.autoscaling.minReplicas' is required" .Values.deployment.autoscaling.minReplicas }}
  maxReplicas: {{ required "value 'deployment.autoscaling.maxReplicas' is required" .Values.deployment.autoscaling.maxReplicas }}
  {{- if or (.Values.deployment.autoscaling.targetCPUUtilizationPercentage) (.Values.deployment.autoscaling.targetMemoryUtilizationPercentage) }}
  metrics:
  {{- if .Values.deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployment.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployment.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- end }}
  {{- with .Values.deployment.autoscaling.behavior }}
  behavior:
    {{- with .scaleDown }}
    scaleDown:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .scaleUp }}
    scaleUp:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}